// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmbgoqjOWeeG8jfzmyv0WKwuDj0e_fo_Y',
    appId: '1:1015588608849:web:afc05a5a0c2ae6de5ed170',
    messagingSenderId: '1015588608849',
    projectId: 'blooddonortest-76bd4',
    authDomain: 'blooddonortest-76bd4.firebaseapp.com',
    storageBucket: 'blooddonortest-76bd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFOoN2Ax1dTlBE7B7ND5ToN-F1NGer4M',
    appId: '1:1015588608849:android:78bfefdfd02964fd5ed170',
    messagingSenderId: '1015588608849',
    projectId: 'blooddonortest-76bd4',
    storageBucket: 'blooddonortest-76bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4jz1s6sAWL8HBXYKaBAdWh1K-oQml2I',
    appId: '1:1015588608849:ios:1d8ee196810b751e5ed170',
    messagingSenderId: '1015588608849',
    projectId: 'blooddonortest-76bd4',
    storageBucket: 'blooddonortest-76bd4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh4jz1s6sAWL8HBXYKaBAdWh1K-oQml2I',
    appId: '1:1015588608849:ios:1d8ee196810b751e5ed170',
    messagingSenderId: '1015588608849',
    projectId: 'blooddonortest-76bd4',
    storageBucket: 'blooddonortest-76bd4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmbgoqjOWeeG8jfzmyv0WKwuDj0e_fo_Y',
    appId: '1:1015588608849:web:e0fc0c010d1cd6b95ed170',
    messagingSenderId: '1015588608849',
    projectId: 'blooddonortest-76bd4',
    authDomain: 'blooddonortest-76bd4.firebaseapp.com',
    storageBucket: 'blooddonortest-76bd4.appspot.com',
  );

}